### PR TITLE
Fix firebase functions, remove explicit any

### LINKED ISSUE #496: Un-ignore and fix biome suspicious/noExplicitAny lint error
## Description
Un-ignore and fix biome `suspicious/noExplicitAny` lint error.

## Blocked by
- [ ] #477

## Checklist
Before submitting this ticket, make sure this ticket:
- [x] Is **labelled properly** - if this is a refactor, add the label!
- [x] Has the **correct project assigned to it**.
- [x] Has an **assigned milestone**.

And lastly:
- [ ] Once someone picks up this ticket, **make sure to assign it**.

### PR DESCRIPTION
**Pull request by bensengupta**
## Description

- Fixes firebase functions
- Removes explicit any

## Linked Issues
- Fixes #496

### Before

Screenshot 2025-05-07 at 8 59 08 AM
Screenshot 2025-05-07 at 8 58 47 AM

### After

Screenshot 2025-05-07 at 8 57 23 AM
Screenshot 2025-05-07 at 8 56 43 AM

## Reviewer Checklist
When reviewing this PR, make sure to keep the following in mind:
- This PR should not span too many unrelated tickets or changes.
  - If it does, consider breaking it up into smaller PRs.
- Is the code coverage acceptable?
- Does the preview deployment work as expected?
- Does this PR pass all tests?
- Does this PR have a clear list of issues that it closes?
- Does the code follow the style guidelines of the project?

## Author Checklist
Before opening this PR, make sure the PR:
- [ ] Has an **assignee or group of assignees**.
- [ ] Has a **reviewer or a group of reviewers**.
- [ ] Is **labelled properly**.
- [ ] Has an **assigned milestone**.

Additionally, make sure that:
- [ ] I have commented my code, particularly in hard-to-understand areas.
- [ ] I have made corresponding changes to the documentation.
- [ ] My changes generate no new warnings.
- [ ] I have added tests that prove my fix is effective or that my feature works.
- [ ] New and existing unit tests pass locally with my changes.
- [ ] Any dependent changes have been merged and published in downstream modules.

### CODE REVIEW

File: functions/src/apple.ts [hunk 1]
```diff
@@ -16,14 +16,13 @@ const signerKeyPassphrase =
 const teamIdentifier = process.env.APPLE_WALLET_CERTS_TEAM_ID;
 
 // apple wallet ticket
-export const createTicket = onCall(async (_, res) => {
-	const context = res as Context;
-	if (!context?.auth) {
+export const createTicket = onCallCustom(async (req) => {
+	if (!req.auth) {
```
Comment (bensengupta) [inline functions/src/apple.ts:20]: Couple things:
- `onCallCustom` is a small wrapper over firebase's `onCall` with safer typing (uses `unknown` instead of `any`) and handles zod validation errors
- In firebase functions Gen 2, the handler is no longer `(data, context) => {...}` but `(req, res) => {...}` and `auth` is on the `req` object

File: functions/src/env.d.ts [hunk 2]
```diff
@@ -0,0 +1,8 @@
+import "firebase-admin/auth";
+
+declare module "firebase-admin/auth" {
+	interface DecodedIdToken {
+		admin?: boolean;
+		email?: string;
```
Comment (bensengupta) [inline functions/src/env.d.ts:6]: Adds `admin` and `email` to `req.auth.token`

**Review by juancwu — APPROVED** [review]
