### PR TITLE
fixes dark mode bug

### LINKED ISSUE #478: Dark mode is enabled while not all components are compatible
## Description
As of now, the entire app is not compatible with colour mode switching. Light mode should be forced so that the UI still looks decent.

## Reproduction
1. Start development server
2. Open the home page

## Screenshots
Image

## Checklist
Before submitting this ticket, make sure this ticket:
- [x] Is **labelled properly**.
- [x] Has the **correct project assigned to it**.
- [x] Has an **assigned milestone**.

And lastly:
- [ ] Once someone picks up this ticket, **make sure to assign it to a developer**.

### PR DESCRIPTION
**Pull request by sharibkabani**
## Description
sets default theme to light and handles case if resolved theme is undefined

## Linked Issues
- Fixes #478 

## Testing
N/A

## Reviewer Checklist
When reviewing this PR, make sure to keep the following in mind:
- This PR should not span too many unrelated tickets or changes.
  - If it does, consider breaking it up into smaller PRs.
- Is the code coverage acceptable?
- Does the preview deployment work as expected?
- Does this PR pass all tests?
- Does this PR have a clear list of issues that it closes?
- Does the code follow the style guidelines of the project?

## Author Checklist
Before opening this PR, make sure the PR:
- [X] Has an **assignee or group of assignees**.
- [X] Has a **reviewer or a group of reviewers**.
- [X] Is **labelled properly**.
- [X] Has an **assigned milestone**.

Additionally, make sure that:
- [ ] I have commented my code, particularly in hard-to-understand areas.
- [ ] I have made corresponding changes to the documentation.
- [ ] My changes generate no new warnings.
- [ ] I have added tests that prove my fix is effective or that my feature works.
- [ ] New and existing unit tests pass locally with my changes.
- [ ] Any dependent changes have been merged and published in downstream modules.

### CODE REVIEW

**Comment by juancwu** [comment]
Should wait for #485 to merge and all the formatting PRs before merging this one to keep the files formatted. Avoid merge conflicts.

**Review by bensengupta — APPROVED** [review]

File: src/components/ui/color-mode.tsx [hunk 1]
```diff
@@ -11,7 +10,12 @@ export interface ColorModeProviderProps extends ThemeProviderProps {}
 
 export function ColorModeProvider(props: ColorModeProviderProps) {
 	return (
-		<ThemeProvider attribute="class" disableTransitionOnChange {...props} />
+		<ThemeProvider
+			attribute="class"
+			defaultTheme="light"
+			disableTransitionOnChange
+			{...props}
+		/>
```
Comment (juancwu) [inline src/components/ui/color-mode.tsx:18]: We can just force the theme to be "light" instead of having a default. I think the prop is `forcedTheme="light"`. This will just remove the need to even support the `useColorMode` hook. It is very unlikely that we will even make a dark theme.

**Review by juancwu — CHANGES_REQUESTED** [review]

**Review by juancwu — APPROVED** [review]

**Review by bensengupta — APPROVED** [review]
